### ISSUE TITLE
some ideas

### ISSUE THREAD

**Issue by ohyeah521** [darsto/synology_surveillance_unlock#1]
This patching method is too troublesome. I have done it before, but was forced to delete it later. I think that reverse analyzing its authentication protocol and setting up an authentication server locally should be a perfect solution.

```
libssutils.so
SSKeyMgr::AddKey(SSKeyMgr **this, const Json::Value *a2, __int32 a3)
SSKeyMgr::RegularActivateLicense(SSKeyMgr *this)

libssshm.so
SendActivationRequest(const Json::Value *a1, Json::Value *a2, int a3)
DecryptActivationRet(__int64 a1, __int64 a2, int a3)
```

**Comment by darsto** [comment]
no thanks
